INSERT INTO question(
     category, difficulty_level, option1, option2, option3, option4, question_title, right_answer)
      VALUES 
         -- Java Questions
         ('Java','Easy','int','float','double','char','Which data type is used to store whole numbers?','int'),
         ('Java','Easy','System.out.println','print','echo','cout','Which statement is used to print in Java?','System.out.println'),
         ('Java','Easy','class','object','method','variable','What is an instance of a class called?','object'),
         ('Java','Easy','public','private','protected','default','Which access modifier allows access from anywhere?','public'),
         ('Java','Easy','int','Integer','float','String','Which data type is used to store text?','String'),
         ('Java','Medium','public','private','protected','default','Which access modifier allows access within the same package?','default'),
         ('Java','Medium','Overloading','Overriding','Inheritance','Polymorphism','What is it called when two methods have the same name but different parameters?','Overloading'),
         ('Java','Medium','JVM','JRE','JDK','JIT','Which component is responsible for executing Java bytecode?','JVM'),
         ('Java','Medium','StringBuilder','StringBuffer','String','StringTokenizer','Which class is mutable in Java?','StringBuilder'),
         ('Java','Medium','int','Integer','float','double','Which is a wrapper class for primitive int?','Integer'),
         ('Java','Hard','Heap','Stack','Method Area','Class Loader','Where are objects stored in memory in Java?','Heap'),
         ('Java','Hard','Checked Exception','Unchecked Exception','Error','Runtime Exception','Which type of exception must be handled explicitly?','Checked Exception'),
         ('Java','Hard','Abstract Class','Interface','Enum','Annotation','Which feature is used to achieve multiple inheritance in Java?','Interface'),
         ('Java','Hard','Garbage Collector','JVM','JIT','Compiler','Which component is responsible for memory management in Java?','Garbage Collector'),
         ('Java','Hard','synchronized','volatile','transient','final','Which keyword is used to prevent thread interference?','synchronized'),

         -- Python Questions
         ('Python','Easy','list','tuple','dictionary','set','Which data structure is ordered and mutable?','list'),
         ('Python','Easy','def','class','lambda','return','Which keyword is used to define a function in Python?','def'),
         ('Python','Easy','True','False','None','0','What is the boolean value for "yes" in Python?','True'),
         ('Python','Easy','for','while','do-while','foreach','Which loop is used to iterate over a sequence in Python?','for'),
         ('Python','Easy','len()','size()','count()','length()','Which function is used to get the length of a list in Python?','len()'),
         ('Python','Medium','list','tuple','dictionary','set','Which data structure is unordered and mutable?','set'),
         ('Python','Medium','__init__','__str__','__repr__','__del__','Which method is called a constructor in Python?','__init__'),
         ('Python','Medium','lambda','def','map','filter','Which keyword is used to create anonymous functions?','lambda'),
         ('Python','Medium','is','==','!=','in','Which operator checks for object identity?','is'),
         ('Python','Medium','pip','conda','virtualenv','wheel','Which tool is used to install Python packages?','pip'),
         ('Python','Hard','O(1)','O(n)','O(log n)','O(n^2)','What is the time complexity of searching in a dictionary?','O(1)'),
         ('Python','Hard','try','except','finally','raise','Which block is always executed in exception handling?','finally'),
         ('Python','Hard','Decorator','Generator','Iterator','Context Manager','Which feature is used to modify the behavior of a function?','Decorator'),
         ('Python','Hard','__name__','__main__','__file__','__init__','Which variable is used to check if a script is run directly?','__name__'),
         ('Python','Hard','list comprehension','generator expression','lambda function','map function','Which feature is used for memory-efficient iteration?','generator expression'),

         -- PHP Questions
         ('PHP','Easy','echo','print','printf','write','Which statement is used to output text in PHP?','echo'),
         ('PHP','Easy','$','@','#','%','Which symbol is used to declare a variable in PHP?','$'),
         ('PHP','Easy','include','require','import','load','Which keyword is used to include files in PHP?','include'),
         ('PHP','Easy','array()','list()','dict()','set()','Which function is used to create an array in PHP?','array()'),
         ('PHP','Easy','strlen()','length()','size()','count()','Which function is used to get the length of a string in PHP?','strlen()'),
         ('PHP','Medium','GET','POST','PUT','DELETE','Which HTTP method is used to send data to the server in PHP?','POST'),
         ('PHP','Medium','isset()','empty()','is_null()','is_set()','Which function checks if a variable is set and not null?','isset()'),
         ('PHP','Medium','session_start()','session_begin()','start_session()','begin_session()','Which function is used to start a session in PHP?','session_start()'),
         ('PHP','Medium','PDO','MySQLi','ODBC','ADOdb','Which extension is used for database access in PHP with object-oriented support?','PDO'),
         ('PHP','Medium','foreach','for','while','do-while','Which loop is specifically used to iterate over arrays in PHP?','foreach'),
         ('PHP','Hard','try','catch','finally','throw','Which block is used to handle exceptions in PHP?','catch'),
         ('PHP','Hard','__construct','__destruct','__call','__invoke','Which method is called automatically when an object is created in PHP?','__construct'),
         ('PHP','Hard','trait','interface','abstract class','namespace','Which feature is used to achieve code reuse in PHP?','trait'),
         ('PHP','Hard','md5()','sha1()','hash()','crypt()','Which function is used to generate a hash in PHP?','hash()'),
         ('PHP','Hard','Composer','Packagist','PEAR','PHAR','Which tool is used for dependency management in PHP?','Composer'),

         -- JavaScript Questions
         ('JavaScript','Easy','var','let','const','function','Which keyword is used to declare a variable in JavaScript?','var'),
         ('JavaScript','Easy','console.log','print','echo','write','Which statement is used to print in JavaScript?','console.log'),
         ('JavaScript','Easy','function','arrow function','class','object','Which keyword is used to define a function in JavaScript?','function'),
         ('JavaScript','Easy','true','false','null','undefined','What is the boolean value for "yes" in JavaScript?','true'),
         ('JavaScript','Easy','for','while','do-while','foreach','Which loop is used to iterate over a sequence in JavaScript?','for'),
         ('JavaScript','Medium','let','var','const','none','Which keyword is block-scoped and can be reassigned?','let'),
         ('JavaScript','Medium','==','===','!=','!==','Which operator checks for both value and type equality?','==='),
         ('JavaScript','Medium','map()','filter()','reduce()','forEach()','Which array method is used to transform each element in JavaScript?','map()'),
         ('JavaScript','Medium','Promise','Callback','Async/Await','Event Loop','Which feature is used for asynchronous programming in JavaScript?','Promise'),
         ('JavaScript','Medium','JSON.parse()','JSON.stringify()','JSON.decode()','JSON.encode()','Which method is used to convert a JSON string to an object?','JSON.parse()'),
         ('JavaScript','Hard','Closure','Callback','Promise','Event Loop','Which feature allows a function to access variables from its outer scope?','Closure'),
         ('JavaScript','Hard','try','catch','finally','throw','Which block is used to handle exceptions in JavaScript?','catch'),
         ('JavaScript','Hard','prototype','class','constructor','object','Which feature is used to implement inheritance in JavaScript?','prototype'),
         ('JavaScript','Hard','setTimeout','setInterval','clearTimeout','clearInterval','Which function is used to execute code after a delay in JavaScript?','setTimeout'),
         ('JavaScript','Hard','Webpack','Babel','NPM','ESLint','Which tool is used for bundling JavaScript modules?','Webpack');